### ISSUE TITLE
Design Improvement List

### ISSUE THREAD

**Issue by stink3finger** [levelkdev/BC-DAPP#10]
### General

- [ ] Change fonts according to design `SF Pro Text - Semibold` ,`SF Pro Text - Medium` and `SF Pro Text - Regular`
- [x] Chart Widget and Order Form Widget should only have 24px margin between each other

### Header

- [x] Replace the current Header logo with one SVG file: [DXdao.svg.zip](https://github.com/levelkdev/BC-DAPP/files/3673913/DXdao.svg.zip)

### Buy/Sell Widget

- [x] Buy description should have the color #536DFE instead of `blue`
- [x] Replace current DXD Circle Icon with: [dxdao.svg.zip](https://github.com/levelkdev/BC-DAPP/files/3674264/dxdao.svg.zip)
- [x] Replace current Ether Circle Icon with: [ether.svg.zip](https://github.com/levelkdev/BC-DAPP/files/3674265/ether.svg.zip)

### Trade History

- [x] A row should have a height of 40px instead of current 37px
- [ ] Currently, a row has a padding-left and padding-right of 15px, but is should be 24px
- [x] The timestamp should be a hyperlink to etherscan´s transaction detail view
- [x] The Time Column should be aligned to the right instead to the left
- [x] Trade History Widget should have a padding-bottom of 24px instead of 15px
- [ ] If we have more then 4 rows in the list, we should show a scrollbar on the right
- [x] Header description of a column should have the color #BDBDBD

### Footer

- [ ] Connect latest git commit and add the date, so users know if the frontend got updated by the dao. Add a Hyperlink to the `Dxdao Version 5907d81 - 03.09.2019` which will bring you to the latest commit version
- [x] Replace twitter icon with reddit: [reddit.svg.zip](https://github.com/levelkdev/BC-DAPP/files/3674162/reddit.svg.zip)
- [x] Replace twitter icon with telegram: [telegram.svg.zip](https://github.com/levelkdev/BC-DAPP/files/3674161/telegram.svg.zip)
- [x] Add Hyperlink to `Forum` --> https://daotalk.org/c/daos/dx-dao
- [x] Add Hyperlink to `Alchemy` --> which should point to https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a
- [x] Add Hyperlink to twitter icon --> https://twitter.com/dxdao_
- [x] Add Hyperlink to Reddit icon --> https://www.reddit.com/r/dxdao/
- [x] Add Hyperlink to Telegram icon --> https://t.me/dxDAO

**Comment by pimato** [comment]
will be done via small issues instead of a big one.
