### ISSUE TITLE
Add Wallet Connect support

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#110]
Currently only Metamask is supported

**Comment by pimato** [comment]
Uniswap has wallet connect integrated which could be a good reference:
https://github.com/Uniswap/uniswap-frontend

**Comment by pimato** [comment]
It seems like I have issues with wallet connect:
<img width="561" alt="Screenshot 2020-04-06 at 12 16 34" src="https://user-images.githubusercontent.com/5337809/78548178-9f875100-7800-11ea-96d2-c6d47a9c950c.png">

**Comment by AugustoL** [comment]
@pimato this can be closed, right? later I will inprove the .env var handling to make it easier
