### ISSUE TITLE
Disconnecting from Metamask results in app crashes

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#114]
steps for reprodcution:
1) set 1 in the inputfield
2) Click on Connect Wallet and Connect through web3-react
3) disconnect metamask
4) Error:
<img width="1075" alt="Screenshot 2020-04-03 at 23 27 13" src="https://user-images.githubusercontent.com/5337809/78406328-ae081980-7602-11ea-9d3b-85d8f44974ab.png">

**Comment by tspoff** [comment]
Probably related to the ethers -> web3 conversion. Will look into

**Comment by tspoff** [comment]
At some point the metamask connector overrides the backup connector
![image](https://user-images.githubusercontent.com/5606917/78457158-2d830080-7676-11ea-864f-221fd660e015.png)
