### ISSUE TITLE
App crashes through clicking in the inputfield and the disabled button

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#118]
Okay this is a really weird one:

steps to reproduce:

1) Click on the inputfield
2) Click on the disabled "Buy DXD" Button
3) Repeat until "Signal transaction" view is showing and app crashes

result:
<img width="1117" alt="Screenshot 2020-04-04 at 11 18 32" src="https://user-images.githubusercontent.com/5337809/78423392-471c4c00-7666-11ea-9605-b53b47fcc268.png">

**Comment by tspoff** [comment]
I guess onClick still fires even in the component is disabled? @jpkcambridge do you know how this works?

I can just check isActive() in the onClick in any case
