### ISSUE TITLE
Deploy a kovan version with the potential final configuration

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#129]
@tspoff can you post the configuration here!

**Comment by tspoff** [comment]
`Deploy DAT: {
  "initReserve": "100000000000000000000000",
  "currency": "0x0000000000000000000000000000000000000000",
  "initGoal": "15000000000000000000000",
  "buySlopeNum": "1",
  "buySlopeDen": "69459059788300000000000",
  "investmentReserveBasisPoints": "1000",
  "revenueCommitmentBasisPoints": "1000",
  "control": "0x5952e79E71c079a12C98b437C6E9358e15B988f9",
  "beneficiary": "0x5952e79E71c079a12C98b437C6E9358e15B988f9",
  "feeCollector": "0x5952e79E71c079a12C98b437C6E9358e15B988f9",
  "name": "dxDAO Token",
  "symbol": "DXD",
  "minInvestment": "10000000000000000"
}
`

**Comment by jpkcambridge** [comment]
Updated config per chat:

Deploy DAT: {
"initReserve": "85000  000 000 000 000 000 000",
"currency": "0x0000000000000000000000000000000000000000",
"initGoal": "2500 000 000 000 000 000 000",
"buySlopeNum": "1",
"buySlopeDen": “46641 791 000 000 000 000 000",
"investmentReserveBasisPoints": "1000",
"revenueCommitmentBasisPoints": "1000",
"control": "0x5952e79E71c079a12C98b437C6E9358e15B988f9",
"beneficiary": "0x5952e79E71c079a12C98b437C6E9358e15B988f9",
"feeCollector": "0x5952e79E71c079a12C98b437C6E9358e15B988f9",
"name": "dxDAO Token",
"symbol": "DXD",
"minInvestment": "1 000 000 000 000 000"
}

**Comment by AugustoL** [comment]
closed on #145
