### ISSUE TITLE
Issue with Supported Chain ids

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#167]
Hey Augusto, 

it seems like we had an update regarding the .env file.

I have change my .env to this:

```
# React development variables
REACT_APP_MARKET_API_URL=https://api.coingecko.com/api/v3

REACT_APP_SUBGRAPH_URL_1="https://api.thegraph.com/subgraphs/name/balancer-labs/balancer"
REACT_APP_SUBGRAPH_URL_42="https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-kovan"

REACT_APP_KEY_MNEMONIC="fetch spy vague picture winner cabin romance sense salon scheme chronic chef"
REACT_APP_KEY_INFURA_API_KEY="5dab3f3d5ed94017a1fc5a77cf9f34dd"
REACT_APP_ETH_NETWORK="kovan" or "develop"

# Override network rpc urls here
# REACT_APP_SUPPORTED_NETWORK_1="https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_3="https://ropsten.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_4="https://rinkeby.infura.io/v3/xxxxxxxxxxxxxxxxxx"
REACT_APP_SUPPORTED_NETWORK_42="https://kovan.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_66="http://localhost:8545"

# NodeJS environment to use
NODE_ENV="development"

SKIP_PREFLIGHT_CHECK=true```

**Comment by pimato** [comment]
but I am still getting, when I try to do `yarn start`:

<img width="1058" alt="Screenshot 2020-04-08 at 10 33 57" src="https://user-images.githubusercontent.com/5337809/78762696-7a235000-7984-11ea-9960-daca0de94e19.png">

**Comment by pimato** [comment]
`# React development variables
REACT_APP_MARKET_API_URL=https://api.coingecko.com/api/v3

REACT_APP_SUBGRAPH_URL_1="https://api.thegraph.com/subgraphs/name/balancer-labs/balancer"
REACT_APP_SUBGRAPH_URL_42="https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-kovan"

REACT_APP_KEY_MNEMONIC="fetch spy vague picture winner cabin romance sense salon scheme chronic chef"
REACT_APP_KEY_INFURA_API_KEY="5dab3f3d5ed94017a1fc5a77cf9f34dd"
REACT_APP_ETH_NETWORK="kovan"

# Override network rpc urls here
# REACT_APP_SUPPORTED_NETWORK_1="https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_3="https://ropsten.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_4="https://rinkeby.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_42="https://kovan.infura.io/v3/xxxxxxxxxxxxxxxxxx"
# REACT_APP_SUPPORTED_NETWORK_66="http://localhost:8545"

# NodeJS environment to use
NODE_ENV="development"

SKIP_PREFLIGHT_CHECK=true
`

**Comment by pimato** [comment]
<img width="1080" alt="Screenshot 2020-04-08 at 16 00 45" src="https://user-images.githubusercontent.com/5337809/78793092-38a99980-79b2-11ea-9058-4ac5397e069c.png">

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @pimato)
