### ISSUE TITLE
WalletConnect doesn`t show QR-Code on dxtest.eth.link

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#187]
<img width="2201" alt="Screenshot 2020-04-08 at 22 32 40" src="https://user-images.githubusercontent.com/5337809/78830894-06fff500-79e9-11ea-949d-ac60d12901d1.png">

**Comment by pimato** [comment]
seems like the QR code is not a problem right now but rather this:
<img width="2135" alt="Screenshot 2020-04-09 at 12 27 14" src="https://user-images.githubusercontent.com/5337809/78885816-8202f300-7a5d-11ea-8aff-475bc052901c.png">

**Comment by AugustoL** [comment]
this was fixed in #197 , right @pimato ?

**Comment by pimato** [comment]
once we merge this: https://github.com/levelkdev/BC-DAPP/pull/197

**Comment by pimato** [comment]
fixed with https://github.com/levelkdev/BC-DAPP/pull/197
