### ISSUE TITLE
Form state should reset when switching account

### ISSUE THREAD

**Issue by tspoff** [levelkdev/BC-DAPP#195]
1. Start TX as one account.
2. Switch to a new account while TX is pending.
3. Chart state is still the same, but the information is no longer relevant to active account.

<img width="346" alt="Screen Shot 2020-04-08 at 7 33 59 PM" src="https://user-images.githubusercontent.com/5606917/78846017-027b1280-79d0-11ea-99ee-7009d65c3a28.png">

### Easiest solution:
Reset form data on account switch

### Harder solution:
Track form data on a per-account basis, and track what account a TX belongs to (which already happens, but needs more metadata for this)

(This way, if the user goes back to other account - they will still have their previous information)

**Comment by AugustoL** [comment]
Tried to fix this in #220 but PR got closed.
