### ISSUE TITLE
Fix wallet connect issue

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#214]
<img width="666" alt="Screenshot 2020-04-16 at 15 11 17" src="https://user-images.githubusercontent.com/5337809/79460032-8b0f3980-7ff4-11ea-9ec8-fff742605a7a.png">

**Comment by pimato** [comment]
seems like with the new version on https://dxtest.eth.link/#/ it seems to work just fine now.

**Comment by pimato** [comment]
@tspoff @AugustoL @jpkcambridge can you guys confirm?

**Comment by AugustoL** [comment]
Yes, magically solved!
