### ISSUE TITLE
ETH Balance on Local Deployment Wrong

### ISSUE THREAD

**Issue by jpkcambridge** [levelkdev/BC-DAPP#245]
![Screen Shot 2020-04-25 at 1 38 58 PM](https://user-images.githubusercontent.com/874683/80311454-ad9c1200-87ad-11ea-804a-05a22ccb8ddb.png)

**Comment by AugustoL** [comment]
Using the recommened account for testing (The fourth account generated by ganache-cli) fixs the issue. Using the index 0 account seems to return the wrong balance. Could be related to https://github.com/trufflesuite/ganache-cli/issues/719
