### ISSUE TITLE
[Local] Bought a lot of DXD, sold all and bonding curve still has ETHER

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#261]
<img width="953" alt="Screenshot 2020-04-27 at 23 53 14" src="https://user-images.githubusercontent.com/5337809/80424602-5f3c5f80-88e2-11ea-8cbc-28eb36cbe585.png">

**Comment by AugustoL** [comment]
@pimato I think the ETH you saw it belongs to the reserve, I try to reproduce it buying a bit over the kickstarter period and it worked fine.
buy:
![image](https://user-images.githubusercontent.com/7763867/80494645-4745f980-893d-11ea-94d3-b4a117267b1e.png)
sell:
![image](https://user-images.githubusercontent.com/7763867/80494674-4f059e00-893d-11ea-8b61-9431497c2ee9.png)

BUT the price after the operations is 0.0000 DXD/ETH so maybe we still have a bug here but not related with the ETH balance in the curve, but with the price calculation after this crazy operations.
