### ISSUE TITLE
WalletConnect does not generate QR Code

### ISSUE THREAD

**Issue by nicoelzer** [levelkdev/BC-DAPP#278]
Tested on https://dxtest.eth.link/#/exchange

<img width="730" alt="Bildschirmfoto 2020-05-02 um 15 06 34" src="https://user-images.githubusercontent.com/1383195/80864974-84d0bc80-8c86-11ea-88c3-301b76684be2.png">

**Comment by pimato** [comment]
works now! Can you confirm @nicoelzer ?

**Comment by nicoelzer** [comment]
@pimato yes, works
