### ISSUE TITLE
Local environment configuration

### ISSUE THREAD

**Issue by nicoelzer** [levelkdev/BC-DAPP#282]
- "Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js". -> Rename truffle.js to truffle-config.js
- Error: Could not find @openzeppelin/contracts-ethereum-package/contracts/token/ERC20/IERC20.sol from any sources; imported from /Users/user//BC-DAPP/BC-DAPP/contracts/DecentralizedAutonomousTrust.sol -> Add @openzeppelin/contract to dependencies
- REACT_APP_SUPPORTED_NETWORK_x are commented. Probably not needed?
- Documentation says "BCAPP_KEY_MNEMONIC" .env.sample has "REACT_APP_KEY_MNEMONIC"
- .README formatting

**Comment by AugustoL** [comment]
This issues are solved in current develop branch.
