### ISSUE TITLE
Price should not be [Number] [Token] but rather [Number] [Base]/[Quote]

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#50]
Currently:

<img width="321" alt="Screenshot 2020-03-18 at 20 19 51" src="https://user-images.githubusercontent.com/5337809/76998718-d7178180-6955-11ea-9c0e-424f559eb15f.png">

Should:

<img width="421" alt="Screenshot 2020-03-18 at 20 20 12" src="https://user-images.githubusercontent.com/5337809/76998779-e7c7f780-6955-11ea-9fcc-6262ab24a963.png">

**Comment by jpkcambridge** [comment]
@pimato If you are paying in ETH, shouldn't the price be displayed as `1.502 ETH/DXD` ?  Also, when I do some quick looks at sites like Coinmarketcap and Coinbase, I think they all quote price by just using the base currency.

**Comment by pimato** [comment]
If you are paying in ETH -> ETH Quote currency and DXD Base currency

very common is Base Currency/Quote Currency -> DXD/ETH

**Comment by tspoff** [comment]
![image](https://user-images.githubusercontent.com/5606917/78171241-2c599580-7422-11ea-8345-b9815a06c7d2.png)
