### ISSUE TITLE
Wrong use of units in dapp

### ISSUE THREAD

**Issue by AugustoL** [levelkdev/BC-DAPP#55]
At this moment the dapp is always using WEI units, where WEI units should be use only when we communicate to the contracts and in the UI it should always display ETH units (which uses 18 decimals by default)

In order to fix I propose to use the BN library provided by web3, accessible by `web3.utils.BN` and use the methods `web3.utils.fromWei` and `web3.utils.toWei`

**Comment by jpkcambridge** [comment]
@AugustoL I think the Buy/Sell inputs now work with decimal inputs, and I think the user is being now shown the appropriate units.  Can you revisit and see if you notice things that are missing?
