### ISSUE TITLE
Add kickstarter section to chart

### ISSUE THREAD

**Issue by tspoff** [levelkdev/BC-DAPP#76]
* Add static section to start of chart based on initGoal.

**Comment by pimato** [comment]
I believe this is enough to get the fundraiser started:
![BondingCurve-3](https://user-images.githubusercontent.com/5337809/78671513-ad5fd380-78df-11ea-8c80-46bd072bd4f8.png)

https://www.figma.com/file/Qohc4WUA844AND8kXRcEBH/Widgets?node-id=116%3A111
