### ISSUE TITLE
Input ETH in form, show DXD issued instead of 'Pay Amount'

### ISSUE THREAD

**Issue by tspoff** [levelkdev/BC-DAPP#86]
![image](https://user-images.githubusercontent.com/5606917/78280162-a3f0f880-74e6-11ea-9f4f-b9d2cd444dc0.png)

**Comment by pimato** [comment]
<img width="525" alt="Screenshot 2020-04-02 at 19 46 20" src="https://user-images.githubusercontent.com/5337809/78281266-b4bb6180-751a-11ea-81f1-b78be55cd008.png">

This also includes the min buy message
