### ISSUE TITLE
Load Trade History even if user is not connected

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#95]
If we don`t show the trade history, people would think no one ever bought anything here:
<img width="1005" alt="Screenshot 2020-04-03 at 15 19 55" src="https://user-images.githubusercontent.com/5337809/78364956-a32b9580-75be-11ea-8259-2386c954a689.png">

**Comment by tspoff** [comment]
Can't reproduce - seems to work on my browser:

![image](https://user-images.githubusercontent.com/5606917/78370384-9134fd00-7594-11ea-9bd5-2b2a6364e42a.png)

Can others attempt?

For @pimato 
* What browser?
* Does this browser have metamask installed?
* What network is metamask connected to?

**Comment by tspoff** [comment]
Works on a metamask-free browser, thanks to backup connection

![image](https://user-images.githubusercontent.com/5606917/78370523-c17c9b80-7594-11ea-9c3d-47edd388477f.png)

**Comment by AugustoL** [comment]
Working on brave linux with metamask installed but disconnected.
